### ISSUE TITLE
Refactor for Earlier Python Release?

### ISSUE THREAD

**Issue by MS3FGX** [azzeloof/supercon-2022-badge-vm#2]
I see you're making extensive use of the Python 3.10 match case, which certainly makes sense for project like this, but I wonder if requiring the latest release is going to give some people problems at Supercon? It seems that many Linux distros are still using 3.8/3.9, and that assumes you're using the latest release anyway. I wouldn't be surprised if some people only have 3.7 when they show up.

Understanding that it would be a hassle, is there anything in the code that would prevent us from just replacing match case with if statements so we can get wider Python compatibility?

**Comment by hexagon5un** [comment]
Submitted a couple pull requests that implement this.  

One is really simple, and then I went overboard on the assembler.  :)

You can pick/choose.

**Comment by azzeloof** [comment]
Good call, and thanks @hexagon5un for taking care of it!
